### ISSUE TITLE
error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

### ISSUE THREAD

**Issue by Mamun130203** [ms5898/ECBM6040-Project#2]
![Screenshot from 2020-07-10 22-50-09](https://user-images.githubusercontent.com/39679866/87125494-36aaeb80-c2bd-11ea-8ce5-334f136ced54.png)
how to solve this issue? Thanks a lot for your help

**Comment by kir486680** [comment]
@Mamun130203 did you find a way to fix it?

**Comment by EdViktor** [comment]
Same issue here, could you tell me your solution? Thank you.
